In [46]:
#import required libraries and dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [47]:
#view feature names of the dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [48]:
#view target of the dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
#define features and target objects
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [50]:
#create object with new values for prediction
X_new =[[3,5,4,1],[5,4,3,2]]

In [54]:
#use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=10)

In [55]:
#fit data into the logistic regression estimator
logreg.fit(X_feature,Y_target)

C:\Users\Viswajani\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(max_iter=10)

In [56]:
#predict the outcome using logistic regression estimator
logreg.predict(X_new)


array([1, 1])

In [57]:
#import library for model persistance
import pickle as pkl

In [58]:
#use dumps method to persist the model
persist_model =pkl.dumps(logreg)

In [59]:
persist_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eK\nX\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x0e\x00\x00\x00n_features_in_q\x15K\x04X\x08\x00\x00\x00classes_q\x16cnumpy.core.multiarray\n_reconstruct\nq\x17cnumpy\nndarray\nq\x18K\x00\x85q\x19C\x01bq\x1a\x87q\x1bRq\x1c(K\x01K\x03\x85q\x1dcnumpy\ndtype\nq\x1eX\x02\x00\x00\x00i4q\x1fK\x00K\x01\x87q Rq!(K\x03X\x01\x00\x00\x00<q"NNNJ\xff\xff\xff\xffJ\xff\xf

In [63]:
#use joblib.dump to persisit the model to a file
import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl']

In [64]:
#use joblib.load  to persist the model to a file
#create new estimator from the saved model
new_logreg_estimator =joblib.load('regresfilename.pkl')

In [65]:
#view the new estimator
new_logreg_estimator

LogisticRegression(max_iter=10)

In [66]:
#validate and use new estimator to predict
new_logreg_estimator.predict(X_new)

array([1, 1])

## Metrics function to evaluate the accuracy of models prediction
Classification:---> metrics.accuracy_score
                    metrics.average_Precision_score
                    
Clustering:----> metrics.adjusted_rand_score

Regreession:---> metrics.mean_absolute_error
                metrics.mean_squared_error
                metrics.median_absolute_error